version: "3.2"

services:

  common-config: &common_config
    image:  layer1dot5/utxord-wallet-toolchain:latest
    deploy:
      resources:
        limits:
          memory: "6gb"
          cpus: "2.0"
    shm_size: "2gb"
    env_file:
      - .env
    environment:
      - YARN_CACHE_FOLDER=/tmp/yarn_cache
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - "./:/src"

  toolchain-shell:
    profiles: ["donotstart"]
    <<: *common_config
    command: "bash"

  build-wallet:
    profiles: ["donotstart"]
    <<: *common_config
    command: "make clean ext-utxord"

