version: "3.2"

services:

  common-config: &common_config
    image:  layer1dot5/utxord-wallet-toolchain:latest
    deploy:
      resources:
        limits:
          memory: "6gb"
          cpus: "2.0"
    shm_size: "2gb"
    env_file:
      - .env
    environment:
      - YARN_CACHE_FOLDER=/tmp/yarn_cache
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - "./:/src"

  toolchain-shell:
    profiles: ["donotstart"]
    <<: *common_config
    command: "bash"

  build-debug:
    profiles: ["donotstart"]
    <<: *common_config
    command: "bash -c 'pwd ; ls -al'"

  build-wasm-core:
    profiles: ["donotstart"]
    <<: *common_config
    command: "make clean ext-core-lib"

  build-wallet-qa:
    profiles: ["donotstart"]
    <<: *common_config
    command: "make ext-build-clean ext-qa"

  build-wallet-e2e:
    profiles: ["donotstart"]
    <<: *common_config
    command: "make ext-build-clean ext-e2e"

  build-wallet-utxord:
    profiles: ["donotstart"]
    <<: *common_config
    command: "make ext-build-clean ext-utxord"

  build-wallet:
    profiles: ["donotstart"]
    <<: *common_config
    command: "make clean ext-utxord"
