version: "3.2"

services:

  common-config: &common_config
    build:
      context: ./toolchain-image
    deploy:
      resources:
        limits:
          memory: "8gb"
          cpus: "4.0"
    shm_size: "2gb"
    env_file:
      - .env
    environment:
      - YARN_CACHE_FOLDER=/tmp/yarn_cache
    volumes:
      - "./:/src"
      - "./.yarn_cache:/tmp/yarn_cache"

  toolchain-shell:
    <<: *common_config
    build:
      context: ./toolchain-image
      dockerfile: Dockerfile
    image: arrowlabs/wallet-build-tools:latest
